# This is a basic workflow to help you get started with Actions

name: CI build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib install hscript
          haxelib install away3d
          haxelib git polymod https://github.com/larsiusprime/polymod develop
          haxelib install hxCodec
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixelTextureAtlas https://github.com/Smokey555/Flixel-TextureAtlas.git
          haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib install flixel-screenshot-plugin
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile Linux
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Linux Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: 'export/release/linux/bin' 

  buildHTML5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib git polymod https://github.com/larsiusprime/polymod develop
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git flixelTextureAtlas https://github.com/Smokey555/Flixel-TextureAtlas.git
          haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools
          haxelib install flixel-screenshot-plugin
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib install away3d
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile HTML5
        run: haxelib run lime build Project.xml html5 --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish HTMl5 Artifact
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: 'export/release/html5/bin' 

  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib install hscript
          haxelib git polymod https://github.com/larsiusprime/polymod develop
          haxelib install away3d
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixelTextureAtlas https://github.com/Smokey555/Flixel-TextureAtlas.git
          haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib install flixel-screenshot-plugin
          haxelib install hxcpp-debug-server
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
  buildMac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install away3d
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib install hscript
          haxelib git polymod https://github.com/larsiusprime/polymod develop
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixelTextureAtlas https://github.com/Smokey555/Flixel-TextureAtlas.git
          haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib install flixel-screenshot-plugin
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin
